TYPE=VIEW
query=select `simatris`.`fakultas`.`ID` AS `KDFAKMSFAK`,`simatris`.`fakultas`.`NAMA` AS `NMFAKMSFAK`,`simatris`.`fakultas`.`KDPTIMSFAK` AS `KDPTIMSFAK` from `simatris`.`fakultas`
md5=30958eb8a02ea6d9623a370c7186dfe2
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2018-10-10 09:48:45
create-version=1
source=select `fakultas`.`ID` AS `KDFAKMSFAK`,`fakultas`.`NAMA` AS `NMFAKMSFAK`,`fakultas`.`KDPTIMSFAK` AS `KDPTIMSFAK` from `fakultas`
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `simatris`.`fakultas`.`ID` AS `KDFAKMSFAK`,`simatris`.`fakultas`.`NAMA` AS `NMFAKMSFAK`,`simatris`.`fakultas`.`KDPTIMSFAK` AS `KDPTIMSFAK` from `simatris`.`fakultas`
